### ISSUE TITLE
load staticfiles missing in documentation for dashboard.html

### ISSUE THREAD

**Issue by torstenfeld** [talpor/django-dashing#11]
I stumble across this as I tried to add a custom script for a new widget:

When adding 
```
{% block 'scripts' %}
    <script type="text/javascript" src="{% static 'my/custom/script.js' %}"></script>
{% endblock %}
```
to dashing/dashboard.html and calling the web page, I get the following error as ``{% load staticfiles %}`` is missing:
```
TemplateSyntaxError at /dashboard/
Invalid block tag: 'static', expected 'endblock'
```

If it's ok for you, I'd submit a pull request for this.

**Comment by individuo7** [comment]
You're right, please send the pull request to merge. thx :)

**Comment by torstenfeld** [comment]
pull request is ready but I'm waiting for you to merge my previous pull request as I fear to screw things up ;)
