### ISSUE TITLE
looping through dashboard set

### ISSUE THREAD

**Issue by torstenfeld** [talpor/django-dashing#12]
As I now have some more widgets on my dashboard as can be displayed on one page (it's used on a separate computer for monitoring), I modified django-dashing to automatically roll through the different dashboards in the set depending on an URL parameter. 

If you'd like to see this feature in the official django-dashing repo, I'd create that feature and a pull request (might take some days ;) ).

Please let me know if this is of interest. Thanks.

**Comment by individuo7** [comment]
I think it would be a very useful feature! please when you have the final version make a pull request :)
