### ISSUE TITLE
graph chart not displayed correctly when not on first dashboard set

### ISSUE THREAD

**Issue by torstenfeld** [talpor/django-dashing#18]
I'm using the rickshaw chart within the graph widget. When I use it on the first dashboard in a multi-dashboardset scenario, everything is fine. But when the widget is part in one of the other dashboard sets, the chart is cut off:

![2015-02-25_07-49-24](https://cloud.githubusercontent.com/assets/536913/6366242/f1d5d660-bcc2-11e4-8d0f-5368a939c068.png)

I'd create a pull request, but I have to admit, that I do not find the problem. :(

**Comment by individuo7** [comment]
Thanks for report :)  try it, I'll update soon pip to 0.2.4
