### ISSUE TITLE
Dashboard selection modal not showing after update to 0.2.4

### ISSUE THREAD

**Issue by torstenfeld** [talpor/django-dashing#21]
After I updated to 0.2.4, the dashboard selection modal does not show up when pressing CTRL. I switched back to 0.2.3 and it works.

**Comment by individuo7** [comment]
Hi torstenfeld, I effectively changed the ctrl key in the 0.2.4 version, I used rivetsjs to make the binding but I can't reproduce the error.  Can you please give me more information so I am able to reproduce it? I tried with Chrome 41 and Firefox 36 and got nothing. Waiting for answers or feedback!

**Comment by torstenfeld** [comment]
@individuo7 checking right now. might be, that I missed some additional includes as I overwrote the base template.

**Comment by torstenfeld** [comment]
as written on twitter, I missed the changed css as I overwrote dashing.css --> closed
