### ISSUE TITLE
graph.js: Uncaught TypeError: Cannot read property 'beforeRender' of undefined

### ISSUE THREAD

**Issue by torstenfeld** [talpor/django-dashing#23]
Hi @individuo7, 

with your master branch I get *Uncaught TypeError: Cannot read property 'beforeRender' of undefined* in dashing/static/widgets/graph/graph.js line 27:
```beforeRender = this.model.beforeRender || data.beforeRender```

With the demo dashing-config.js I do not have that problem. Please find the widget code of my dashing-config below. Would be nice, if you could point me to the right direction.

```
is.addWidget('analytics_sessions_widget', 'Graph', {
    data: {
        data: [],
        title: 'FC Sessions',
        value: 'loading',
        moreInfo: 'Last week: loading'
    },
    interval: 300000, // 30 min
    col: 1,

    getData: function () {
        var self = this;
        $.get('/api/v1/ga/sessions/test', function(data) {
            var analyticsData = [];
            for(var i=0; i<4; i++) {
                var sessions_string = data[i]['sessions'];
                var sessions_int = parseInt(sessions_string);
                analyticsData.push({
                    x: i,
                    y: sessions_int
                });
                if(i==2) {
                    self.data.moreInfo = 'Last week: ' + sessions_string;
                }
                if(i==3) {
                    self.data.value = sessions_int;
                }
            }
            self.data.data = analyticsData;
            self.data.updatedAt = lastUpdate();
            is.publish('analytics_sessions_widget/render');
        });
        is.publish('analytics_sessions_widget/render');
    }
});
```

**Comment by individuo7** [comment]
Hi, I think that moving the instruction `if (!data) return;` as first line of *dashing-graph binder* should be enough to solve this problem, I saw your pull request but I believe that doing this it will make no longer necessary predefine beforeRender and other methods as empty functions in the scope

Right now I make a push with this fix, if you can please try it and tell me if it works

Regards

**Comment by torstenfeld** [comment]
Hi @individuo7, I just checked your fix and it seems to be working. Thanks! :)
