### ISSUE TITLE
Integrating with mongodb

### ISSUE THREAD

**Issue by jmrjrmv** [talpor/django-dashing#3]
Hi

I wonder how to configure dashing in a 'mongoengine.django.mongo_auth' environment.
Does it work with this kind of environment ?

Thanks for your help.

**Comment by individuo7** [comment]
I have not used mongo_auth, but I think that you can create a custom [permission class](http://django-dashing.readthedocs.org/en/latest/getting-started.html?highlight=PERMISSION_CLASSES#settings) using `mongoengine.django.mongo_auth`
