### ISSUE TITLE
Embedding links into Dashboard?

### ISSUE THREAD

**Issue by lmaloney** [talpor/django-dashing#31]
This isn't really an issue, but rather a question.  I would like to add links inside a widget, but seems I can't do that.  I'm guessing the Widgets are readonly...

I see I can add links on the html page for the dashboard, but is there a way I can do this with a widget?

Like the list widget, put in a clickable link?

(I tried adding href to a key,value in data, but no joy.

**Comment by mverteuil** [comment]
I wrote a widget for this purpose that you can plug into django-dashing:

See my project here at:
https://github.com/mverteuil/widget-party/

**Comment by individuo7** [comment]
Hi, sorry for the lateness and thanks for the answer **mverteill** :), **imaloney** you can try also bind the click event to elements **a** doing something like:

    $('a').click(function(e) {
        e.preventDefault();
        var win = window.open(this.getAttribute('href'), '_blank');
        win.focus();
    })

I have not tested this, but I think it worked

**Comment by lmaloney** [comment]
Thanks, I'll try that...

I started by just putting links in the html body.

kludgey but works for now.

Somebody sent me an email to a widget they made claiming to do this.

Larry

**Comment by mverteuil** [comment]
@lmaloney I've updated my widgets to match the latest design. So you can just leverage the `linklist` from my widget-party project as a drop in solution for this now.

**Comment by lmaloney** [comment]
Hey Guys, I'm trying out widget-party but I've lost the ability to use the
original widgets of Django-Dashing (list,number, clock etc)

I've started an issue here:

https://github.com/mverteuil/widget-party/issues/2

Can you give me any insights?

On Thu, May 7, 2015 at 12:26 PM, M. de Verteuil <notifications@github.com>
wrote:

> I wrote a widget for this purpose that you can plug into django-dashing:
>
> See my project here at:
> https://github.com/mverteuil/widget-party/
>
> On Wed, 6 May 2015 at 20:12 Larry Maloney <notifications@github.com>
> wrote:
>
> > This isn't really an issue, but rather a question. I would like to add
> > links inside a widget, but seems I can't do that. I'm guessing the
> Widgets
> > are readonly...
> >
> > I see I can add links on the html page for the dashboard, but is there a
> > way I can do this with a widget?
> >
> > Like the list widget, put in a clickable link?
> >
> > (I tried adding href to a key,value in data, but no joy.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/talpor/django-dashing/issues/31>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/talpor/django-dashing/issues/31#issuecomment-99988690>
> .
>



-- 
Thank you!

Larry P. Maloney, "Come to the Dojo."
Become a member: http://signup.hackerdojo.com/
-------------------------------------------------------------
LinkedIn: http://www.linkedin.com/in/larrymaloney
Cell: 408-893-0294

**Comment by mverteuil** [comment]
@lmaloney I've responded in that issue
