### ISSUE TITLE
Conditional background color

### ISSUE THREAD

**Issue by wimkerkhoff** [talpor/django-dashing#33]
I'm stuck on something which is maybe trivial... have checked the documentation, source code, and the various examples but no luck.

How can I show a different background color with the Number widget?

Would like to show Green if a number = zero, and Red if number > 0.

Thanks for the cool dashboard by the way :-)

**Comment by mverteuil** [comment]
See my build status widget in widget-party. You can essentially just rip
that off and change the conditions of the binder in the JavaScript.

**Comment by individuo7** [comment]
Hi wimkerkhoff! this feature was (accidentally) disabled in the versions 0.2.5 and 0.2.6 try whit the version 0.2.7, doing some like this should work:

    businessDashboard.addWidget('new_payments_widget', 'Number', {
        color: '#ff9618',
        getData: function () {
            var self = this;
            Dashing.utils.get('new_payments_widget', function(data) {
                $.extend(self.scope, data);
            });
        },
    });

**Comment by wimkerkhoff** [comment]
Hi Individuo7!

I just installed 0.2.7, and the color works on the initial load, thanks for fixing that. However, how do I change when the widget rebinds its data? Should that logic go in the dashing-config, the widget's CSS or the widget's JS?  I'm not sure if this is a JS/CSS trick I can do, or if it requires a change in django-dashing core stuff?

What I want to do is something like:

if (value ==0) {
 background-color: green;
} else if (value < 10) {
 background-color: orange;
} else {
 background-color: red;
}
 
Here is what I have now in dashing-config.js. Actually only the Title and Value seem to rebind... the updatedAt and moreInfo does not, any idea on that?

dashboard.addWidget('NagiosUnhandledHosts', 'Number', {
  color: 'red',
  interval: 1000*2,
   getData: function () {
       $.extend(this.scope, {
       });
      var apple = this;
       $.get('/NagiosUnhandledHosts/', function(data) {
          console.log(data);
          apple.data.title = data.title;
          apple.data.moreInfo = data.moreInfo;
          apple.data.detail = data.detail;
          apple.data.updatedAt = data.updatedAt;
          apple.data.value = data.value;
      });
   }
});

Wim

**Comment by wimkerkhoff** [comment]
mverteuil - I tried your buildstatus.js technique but no luck yet... no errors but background color doesn't change either. Tried some debugging but it seems like the function is not just getting called on the rivet bind. Will keep trying stuff...

**Comment by wimkerkhoff** [comment]
Okay I got it figured out, after looking at the party widget buildstatus widget and reading up on rivets.js docs a bit more.

**Comment by individuo7** [comment]
To do this, I think that you can take two ways, the first is to use a JS/CSS tick like this

    dashboard.addWidget('NagiosUnhandledHosts', 'Number', {
        ...
        getData: function () {
            if (value == 0) {
                $(this.widget).css('background-color', 'green');
            }
            else if (value < 10) {
                $(this.widget).css('background-color', 'orange');
            }
            else {
                $(this.widget).css('background-color', 'red');
            }
            ...
        }
    });

Or the second way is the rivets way, you can create a custom widget or simply overwrite the number template (in /static/widgets/number/number.html), doing something like this:

    <div rv-status-color="value">
        <h1>{ title }</h1>
        <h2>{ value }</h2>
        <p class="detail">{ detail }</p>
        <p class="more-info" rv-if="moreInfo">{ moreInfo }</p>
        <p class="updated-at" rv-if="updatedAt">{ updatedAt }</p>
    </div>

with a binder like:

    rivets.binders['status-color'] = function(el, value) {
        if (value == 0) {
            $(el).css('background-color', 'green');
        }
        else if (value < 10) {
            $(el).css('background-color', 'orange');
        }
        else {
            $(el).css('background-color', 'red');
        }
    };

I have not tried this, but I think it will work

Looking forward for your reply :)

**Comment by wimkerkhoff** [comment]
Hi,

The second approach is working for me now! Thanks for the pointers.

I need to debug yet why the moreInfo and updatedat isn't refreshing properly. It works only for the first load and then not for the future intervals. I don't have time today to look at that, maybe next week. Now that I understand what the CSS/JS is doing behind the scenes with Rivets.js it should be easier.

Wim

**Comment by abakal** [comment]
Hello,

Could you tell me how to get value from detail-field of widget with the rivet.js?
To proceed something like that:

```
rivets.binders['status-color'] = function(el, value) {
    if (value == detail) {
        $(el).css('background-color', 'green');
    }
    else if (value < detail) {
        $(el).css('background-color', 'orange');
    }
    else {
        $(el).css('background-color', 'red');
    }
};
```
Thank you beforehand.
Andrei B.
