### ISSUE TITLE
Suggestion : Use websockets 

### ISSUE THREAD

**Issue by Sshuichi** [talpor/django-dashing#40]
Hi! 
Sending repeatedly AJAX request is not a best practice. 
That's why They introduced Websockets. 
It's not easy to migrate everything now but think about it.

**Comment by individuo7** [comment]
Yes, use websockets should be a good improvement, but Django is not prepared for that, and the idea of django-dashing is be a easy django plug and play dashboard

This is a good article where talk about it https://lincolnloop.com/blog/architecting-realtime-applications/

**Comment by wimkerkhoff** [comment]
uwsgi to the rescue:

http://uwsgi-docs.readthedocs.org/en/latest/articles/OffloadingWebsocketsAndSSE.html
