### ISSUE TITLE
where do you suggest to place dashing-config.js or dashboard.html ?

### ISSUE THREAD

**Issue by pcompassion** [talpor/django-dashing#48]
just curious..

I could place code under my project's `app/dashing/static/dashing/dashing-config.js` 

but `from dashing import <something>` would cause problems when I start to add python codes under `app/dashing/` 

So where do you suggest to place those files?

**Comment by individuo7** [comment]
I do not quite understand the problem :/ anyway you can change the location of dashing-config.js overwriting the main dashing template file https://django-dashing.readthedocs.org/en/v0.3/getting-started.html#template-file

**Comment by pcompassion** [comment]
Here we go again.

I think hard where to place the code related to `dashing` app.  

I think `dashing` directory under `my_project` would be perfect.  

Then I find later I can add python code (custom widget) to the app.  

`from dashing.widget import MyWidget` would confuse python because `dashing` is already installed in virtual environment with the same name `dashing`


Question is, I'm extending the app `dashing` and I'd like to use the sane directory & name for the extension.  and wonder where that might be?  

The question is applicable to other apps than dashing, I'm just curious how people handle such case?

Just fork and use the fork?

**Comment by individuo7** [comment]
Ok, I have not tried, but I think the best option is to use `from __future__ import absolute_import` and do something like `from .dashing.widgets import MyWidget`

**Comment by pcompassion** [comment]
Thanks for the answer.
