### ISSUE TITLE
How to use rickshawgraph extension?

### ISSUE THREAD

**Issue by pcompassion** [talpor/django-dashing#49]
https://gist.github.com/jwalton/6614023 

It has *.coffee *.html *.scss .

django-dashing states ` fully create your own with css, html, and javascript.` 

Can I adapt the `rickshawgraph widget` somehow?

** edit **

I didn't know `dashing` is the root project that inspired django-dashing.. (ok. it's stated on the front page of django-dashing)

There's apparently a python clone.. 
https://github.com/evolvedlight/pydashie

And it uses flask and uses the same `*.coffee *.html *.scss`   
So I assume you could litterally copy and paste the new widgets from `dashing` 

Would it be possible to do similar with `django-dashing` ?

**Comment by individuo7** [comment]
You can use these files as guide, but you can't do a copy paste because django-dashing use the same libraries of original project but the javascript API is different
