### ISSUE TITLE
Problem: other widgets extend this.data, not this.scope

### ISSUE THREAD

**Issue by hmpf** [talpor/django-dashing#56]
The demo, and widgets not hosted here, do this:

 $.extend(self.data, bla);

instead of this:

 $.extend(self.scope, bla);

With 0.3.0, I can only get the latter to work. Will I have to fork for instance the weather-widget, or is this accidentally something that breaks compatibility (ergo a bug) and something that should be flagged to widget-maintainters?

**Comment by individuo7** [comment]
the demo was updated, sorry for that
