### ISSUE TITLE
Own modules

### ISSUE THREAD

**Issue by mliner** [talpor/django-dashing#69]
Hey,

I'm trying to setup this really cool tool. Unfortunatelly I am not able to create my own widgets. I was trying it with the documentation (created own PyPI package with my custom widgets with no success). Is there somebody who has some experience with creating own widgets? Can you share all steps needed?

Also there is a question when I have own widget with python class, how can I pass parameters from js to the python? I want to have one widget to be used with different data passed to python. Is it possible? I didn't find any reasonable example.

Thanks a lot! :-)

**Comment by individuo7** [comment]
You can see the @mverteuil repositoty to take a look on how to create custom widgets via PyPi https://github.com/mverteuil/widget-party

And you can pass parameters from js basically registrating differents urls of the same widget with different parameters https://django-dashing.readthedocs.io/en/latest/getting-started.html#python-widget-classes

Regards :)

**Comment by mliner** [comment]
Hi,

thanks for the response. Regarding passing params from js to python, what is the correct syntax in javascript widget function. Could you please provide an example of such widget?

Regarding custom widgets, I tried a widget party repository, but for some unknown reason it was not working in my case. Unfortunately there is a lack of various examples for this cool project.

Thanx a lot!

**Comment by individuo7** [comment]
Regarding the passing params, this should work on the demo app: http://pastebin.com/KEeQuZ8Q
Regarding the custom widgets, sorry but I have not more demos/implementations of that.
Regards :)
