### ISSUE TITLE
Pushing data into a widget on demand?

### ISSUE THREAD

**Issue by klamont** [talpor/django-dashing#81]
The original shopify version of Dashing allowed the use of CURL to push data from any source into a widget.  This was helpful for things like MOTD, where anyone could display info.  I see in the docs some reference to an API, but I do not see any examples of how to actually use it.  Does this feature exist in django-dashing?

**Comment by individuo7** [comment]
sorry, I delayed this issue for long... it is refer to the same issue as https://github.com/talpor/django-dashing/issues/84 I will close this to continue the conversation there
