### ISSUE TITLE
Is it possible to detect a user action in one widget and act as consequence in other widget?

### ISSUE THREAD

**Issue by romanrdgz** [talpor/django-dashing#83]
For example, clicking over a item in a List widget, and then showing the contents in a different widget. Is that feasible? Could you provide some example to this?

**Comment by individuo7** [comment]
This app does not provide any way to do that in a simple way, you can use jQuery to detect the event and act in consequence something like: `$(".widget-number[data-col='2'][data-row='1']").on('click', ...)`
